---
version: '3.7'

services:
  friendsdrinks-ui:
    image: andyg001/friendsdrinksfrontend:latest
    networks:
      - kafka-network
    volumes:
      - ./dockercompose:/app/config
    ports:
      - "8080:8080"

networks:
  kafka-network:
    external: true
    name: friendsdrinks_default
