---
version: '3.7'

services:
  friendsdrinks-ui:
    image: andyg001/friendsdrinksui:latest
    networks:
      - kafka-network
    volumes:
      - ./dockercompose/config:/app/config
      - ./dockercompose/secret:/app/secret
    ports:
      - "8080:8080"

networks:
  kafka-network:
    external: true
    name: friendsdrinks_default