apiVersion: v1
kind: Service
metadata:
  name: friendsdrinks-ui-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30615
  selector:
    app: friendsdrinks-ui