---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'DNS stack'

Parameters:
  Stage:
    Type: String
    Description: Stage
  ELBDomainName:
    Type: String
    Description: ELB domain name
  HostedZoneId:
    Type: String
    Description: HostedZoneId
  ELBHostedZoneId:
    Type: String
    Description: ELB HostedZoneId

Resources:
  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !Sub "${ELBDomainName}"
        EvaluateTargetHealth: false
        HostedZoneId: !Sub "${ELBHostedZoneId}"
      Comment: "Alias record for ELB"
      HostedZoneId: !Sub "${HostedZoneId}"
      Name: !Sub "${Stage}.friendsdrinksv2.com"
      Region: !Ref 'AWS::Region'
      Type: 'A'
      SetIdentifier: !Sub "${Stage}"



Outputs:
  RecordSet:
    Value: !Ref RecordSet
    Export:
      Name: !Sub "${AWS::StackName}-RecordSet"