---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'DNS stack'

Parameters:
  Stage:
    Type: String
    Description: Stage
  ELBDomainName:
    Type: String
    Description: ELB domain name
  HostedZoneId:
    Type: String
    Description: HostedZoneId

Resources:
  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !Sub '${ELBDomainName}'
        EvaluateTargetHealth: false
      Comment: "Alias record for ELB"
      HostedZoneId: !Sub '${HostedZoneId}'
      Name: !Sub '${Stage}.friendsdrinksv2.com'
      Region: !Ref 'AWS::Region'
      Type: 'A|AAA'


Outputs:
  RecordSet:
    Value: !Ref RecordSet
    Export:
      Name: !Sub "${AWS::StackName}-RecordSet"